name: updater
on:
  schedule:
    # Runs every hour
    - cron: '10-16 * * * 1-6'
  workflow_dispatch:


 jobs:
  update-txt:
    name: Update the text.txt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: index.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "%B %d, %Y" auto-commit
